config/routes.rb
Rails.application.routes.draw do
  resources :enrollments
  get 'home/index'
  devise_for :users, :controllers => { registrations: 'users/registrations', 
  omniauth_callbacks: 'users/omniauth_callbacks'}

  resources :courses do
    resources :lessons
    resources :enrollments, only: [:new, :create]
  end
  resources :users, only: [:index, :edit, :show, :update]

  root 'home#index'
  get 'home/activity'
  #root 'static_pages#landing_page'
  #get 'static_pages/landing_page'
  #get 'static_pages/privacy_policy'
  get "privacy_policy",to:'static_pages#privacy_policy'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/enrollment.rb
class Enrollment < ApplicationRecord

  belongs_to :course
  belongs_to :user

  validates :user, :course, presence: true

  validates_uniqueness_of :user_id, scope: :course_id  #user cant be subscribed to the same course twice
  validates_uniqueness_of :course_id, scope: :user_id  #user cant be subscribed to the same course twice

  validate :cant_subscribe_to_own_course  #user can't create a subscription if course.user == current_user.id
  scope :pending_review, -> { where(rating: [0, nil, ""], review: [0, nil, ""]) }

  extend FriendlyId
  friendly_id :to_s, use: :slugged

  def to_s
    user.to_s + " " + course.to_s
  end

  protected
  def cant_subscribe_to_own_course
    if self.new_record?
      if self.user_id.present?
        if self.user_id == course.user_id
          errors.add(:base, "You can not subscribe to your own course")
        end
      end
    end
  end

end

app/controllers/enrollments_controller.rb
class EnrollmentsController < ApplicationController
  before_action :set_enrollment, only: [:show, :edit, :update, :destroy]
  #before_action :set_coruse, only: [:new, :create]

  def index
    #@enrollments = Enrollment.all
    #@pagy, @enrollments = pagy(Enrollment.all)

    @q = Enrollment.ransack(params[:q])
    @pagy, @enrollments = pagy(@q.result.includes(:user))

    authorize @enrollments
  end

  def show
  end
  def new
    @enrollment = Enrollment.new
  end

  def edit
    authorize @enrollment
  end

  def create
    if @course.price > 0
      flash[:alert] = "You can not access paid courses yet."
      redirect_to new_course_enrollment_path(@course)
    else
      @enrollment = current_user.buy_course(@course)
      redirect_to course_path(@course), notice: "You are enrolled!"
    end
  end

  def update
    authorize @enrollment
    respond_to do |format|
      if @enrollment.update(enrollment_params)
        format.html { redirect_to @enrollment, notice: 'Enrollment was successfully updated.' }
        format.json { render :show, status: :ok, location: @enrollment }
      else
        format.html { render :edit }
        format.json { render json: @enrollment.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    authorize @enrollment
    @enrollment.destroy
    respond_to do |format|
      format.html { redirect_to enrollments_url, notice: 'Enrollment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  private
    # def set_coruse
    #   @course = Course.friendly.find(params[:course_id])
    # end
    def set_enrollment
      @enrollment = Enrollment.friendly.find(params[:id])
    
    end
    def enrollment_params
      params.require(:enrollment).permit(:rating, :review)
    end
end

app/helpers/enrollments_helper.rb
module EnrollmentsHelper
end

app/views/enrollments/_enrollment.html.haml
.card
  .card-header
    .fa.fa-user
    = link_to enrollment.user.username, user_path(enrollment.user)
    .fa.fa-clock
    = time_ago_in_words(enrollment.updated_at)
    .fa.fa-graduation-cap
    = link_to enrollment.course, course_path(enrollment.course)
  .card-body
    .text-warning.fa.fa-star
    %b= enrollment.rating
    .fa.fa-comment
    %small= enrollment.review
  - if current_user
    .card-footer
      - if policy(enrollment).edit?
        = link_to 'Edit Review', edit_enrollment_path(enrollment)

app/views/enrollments/_form.html.haml
-# frozen_string_literal: true
= simple_form_for(@enrollment) do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

  .form-inputs
    = f.input :rating, collection: 1..5, as: :radio_buttons
    = f.input :review

  .form-actions
    = f.button :submit

app/views/enrollments/edit.html.haml
- content_for :title do
  Corsego 
  \| 
  Editing
  = @enrollment.to_s

.card
  .card-header
    %h3
      .text-warning.fa.fa-star
      Add a Review
  .card-body
    = render 'form'
  .card-footer
    = link_to 'Show Review', @enrollment
    \|
    = link_to 'Back to course', course_path(@enrollment.course)

app/views/enrollments/index.html.haml
- content_for :title do
  Corsego 
  \| 
  All Enrollments
%h3
  .text-center
    Enrollments
    .badge.badge-info
      = @enrollments.count
%p

= search_form_for @q do |f|
  = f.search_field :user_email_cont, placeholder: 'user email'
  = f.search_field :course_title_cont, placeholder: 'course title'
  = f.search_field :price_eq, placeholder: 'price'
  = f.search_field :rating_eq, placeholder: 'rating'
  = f.search_field :review_cont, placeholder: 'review'
  = f.submit
= link_to 'refresh', enrollments_path

.table-responsive
  %table.table.table-bordered.table-striped.table-sm
    %thead
      %tr
        %th ID
        %th
          = sort_link(@q, :user_email)
          /.fa.fa-user
          /User
        %th
          bought
          = sort_link(@q, :created_at)
          /.fa.fa-clock
          /.fa.fa-lock-open
          /bought
        %th
          = sort_link(@q, :course_title)
          /.fa.fa-graduation-cap
          /Course
        %th 
          = sort_link(@q, :price)
          /.fa.fa-dollar-sign
          /Price
        %th 
          = sort_link(@q, :updated_at)
          .row
          .text-warning.fa.fa-clock
          Reviewed on
        %th 
          = sort_link(@q, :rating)
          .text-warning.fa.fa-star
          Rating
        %th 
          .text-warning.fa.fa-comment
          Review
        %th
        %th
        %th
  
    %tbody
      - @enrollments.each do |enrollment|
        %tr
          %td= enrollment.id
          %td= link_to enrollment.user, user_path(enrollment.user)
          %td= enrollment.created_at.strftime("%d/%b/%Y, %H:%M")
          %td= link_to enrollment.course, course_path(enrollment.course)
          %td= number_to_currency(enrollment.price)
          %td
            - if enrollment.rating.present?
              = enrollment.updated_at.strftime("%d/%b/%Y, %H:%M")
          %td= enrollment.rating
          %td= enrollment.review
          %td= link_to 'See Review', enrollment
          %td= link_to 'Add Review', edit_enrollment_path(enrollment)
          %td= link_to 'Delete Enrollment', enrollment, method: :delete, data: { confirm: 'Are you sure?' }
!= pagy_bootstrap_nav(@pagy)
%br

app/views/enrollments/new.html.haml
- content_for :title do
  Corsego 
  \| 
  New enrollment

.card
  .card-header
    %h3
      .fa.fa-graduation-cap
      = link_to @course.title, course_path(@course)
      %hr
      .fa.fa-lock-open
      Buy course
  .card-body
    = form_tag course_enrollments_path(@course) do
      = submit_tag "Pay #{@course.price}", class: 'btn btn-lg btn-success'
  .card-footer
    = link_to 'Back', course_path(@course)

app/views/enrollments/show.html.haml
= render 'enrollments/enrollment', enrollment: @enrollment 